update: add README.md
dcTeam7/in_progress pull request #24
Opened 2023-04-12 14:14 UTC by Deborahhm

2023-04-12 14:22 UTC, KevinDik requested changes

2023-04-12 14:22 UTC, KevinDik commented on README.md
@Deborahhm Faltou subir os arquivos para o github

2023-04-12 16:35 UTC, joellacerda commented on README.md
Sim, lembrando que essa é a issue de descrever como rodar localmente o projeto

2023-04-17 22:23 UTC, joellacerda approved these changes

2023-04-18 01:30 UTC, KevinDik approved these changes

2023-04-18 01:31 UTC, merged