I#12
dcTeam7/in_progress pull request #31
Opened 2023-04-18 12:01 UTC by KevinDik

#12 Gostaria de tirar minhas duvidas referente ao componente SortButton

2023-04-18 12:04 UTC, AbraaoAlves commented on src/components/SortButton/SortButton.tsx
> +    setClicked(!clicked)
Vamos precisar usar o botão com um evento de callback, mais ou menos dessa forma:

``` jsx
  <ButtonSeta onChange={(isUp) =>  
      /** fetch sorted list */   } 
   />

```


Para isso você deve usar a prop `onClick` dentro do `handleClick`

2023-04-18 14:32 UTC, KevinDik commented on src/components/SortButton/SortButton.tsx
> +    setClicked(!clicked)
Feito

2023-04-20 01:31 UTC, joellacerda requested changes

2023-04-20 01:31 UTC, joellacerda commented on src/components/SortButton/SortButton.tsx
> +   * Informa o estado do botal
Só um errinho de digitação na documentação
```suggestion
   * Informa o estado do botão
```

2023-04-20 11:03 UTC, KevinDik commented on src/components/SortButton/SortButton.tsx
> +   * Informa o estado do botal
Corrigido @joellacerda

2023-04-20 11:26 UTC, joellacerda approved these changes

2023-04-20 12:17 UTC, AbraaoAlves approved these changes

2023-04-20 12:18 UTC, merged